const ordersData = {
    "orders": [
        {
            "id": 661278,
            "platform": "ps4",
            "deliveryMethod": "Easy",
            "coinCount": 1750000,
            "overallPrice": 71.75,
            "currency": "USD",
            "status": "FINISHED",
            "orderType": "CoinsOrder",
            "labels": [],
            "createdAt": "2024-06-05T15:38:50.977457",
            "coinTransferred": 0,
            "percentTransferred": 0,
            "login": "",
            "psn_password": "",
            "email_password": "",
            "backup_codes": ",,,,,",
            "cashback": 0,
            "cashbackUsed": 0,
        },
        {
            "id": 647257,
            "platform": "ps4",
            "deliveryMethod": "Easy",
            "coinCount": 10000000,
            "overallPrice": 470,
            "currency": "EUR",
            "status": "IN_PROGRESS",
            "orderType": "CoinsOrder",
            "labels": [],
            "createdAt": "2024-04-22T10:06:27.9215",
            "coinTransferred": 0,
            "percentTransferred": 0,
            "login": "",
            "psn_password": "",
            "email_password": "",
            "backup_codes": ",,,,,",
            "cashback": 0,
            "cashbackUsed": 0,
        },
        {
            "id": 647254,
            "platform": "ps4",
            "deliveryMethod": "Easy",
            "coinCount": 10000000,
            "overallPrice": 470,
            "currency": "USD",
            "status": "ERROR",
            "orderType": "CoinsOrder",
            "labels": [],
            "createdAt": "2024-04-22T10:05:00.96088",
            "coinTransferred": 0,
            "percentTransferred": 0,
            "login": "",
            "psn_password": "",
            "email_password": "",
            "backup_codes": ",,,,,",
            "cashback": 0,
            "cashbackUsed": 0,
        },
        {
            "id": 647253,
            "platform": "ps4",
            "deliveryMethod": "Easy",
            "coinCount": 10000000,
            "overallPrice": 470,
            "currency": "USD",
            "status": "ERROR_PAYMENT",
            "orderType": "CoinsOrder",
            "labels": [],
            "createdAt": "2024-04-22T10:04:33.704813",
            "coinTransferred": 0,
            "percentTransferred": 0,
            "login": "",
            "psn_password": "",
            "email_password": "",
            "backup_codes": ",,,,,",
            "cashback": 0,
            "cashbackUsed": 0,
        },
        {
            "id": 647252,
            "platform": "ps4",
            "deliveryMethod": "Easy",
            "coinCount": 10000000,
            "overallPrice": 470,
            "currency": "USD",
            "status": "ACCEPTED",
            "orderType": "CoinsOrder",
            "labels": [],
            "createdAt": "2024-04-22T10:04:33.704813",
            "coinTransferred": 0,
            "percentTransferred": 0,
            "login": "",
            "psn_password": "",
            "email_password": "",
            "backup_codes": ",,,,,",
            "cashback": 0,
            "cashbackUsed": 0,
        },
        {
            "id": 647357,
            "platform": "ps4",
            "deliveryMethod": "Easy",
            "coinCount": 555666,
            "overallPrice": 333,
            "currency": "USD",
            "status": "CLOSED",
            "orderType": "CoinsOrder",
            "labels": [],
            "createdAt": "2024-04-22T10:04:33.704813",
            "coinTransferred": 0,
            "percentTransferred": 0,
            "login": "",
            "psn_password": "",
            "email_password": "",
            "backup_codes": ",,,,,",
            "cashback": 0,
            "cashbackUsed": 0,
        },
    ],
    "total": 349,
    "page": 0,
    "limit": 10,
};

export default ordersData;
