/* eslint-disable @nx/enforce-module-boundaries */
import { IMapStatus } from "@royalfut/interfaces";

export const mapStatus: IMapStatus = {
    waiting_payment: {
        btn_text: "orders.make",
        btn_fnc: "retryOrder",
        status: "waiting_payment",
        label: "orders.unpaid",
        theme: "white",
        image: "/image/status/info.svg",
        description: "orders.unpaid_description",
        body: false,
    },
    error_payment: {
        btn_text: "orders.retry",
        btn_fnc: "retryOrder",
        status: "error_payment",
        label: "orders.failed_title",
        theme: "white",
        image: "/image/status/error.svg",
        description: "orders.failed_description",
        body: false,
    },
    pc_not_supported: {
        btn_text: "orders.retry",
        btn_fnc: "retryOrder",
        status: "pc_not_supported",
        label: "orders.wrong_platform",
        theme: "red",
        image: "/image/status/error.svg",
        description: "orders.wrong_description",
        body: false,
    },
    not_enough_coins_to_start: {
        btn_text: "orders.resume",
        btn_fnc: "openOrder",
        status: "not_enough_coins_to_start",
        label: "orders.not_enough",
        theme: "red",
        image: "/image/status/error.svg",
        description: "orders.not_enough_description",
        body: true,
    },
    no_club_in_fut_web_app: {
        btn_text: "orders.resume",
        btn_fnc: "openOrder",
        status: "no_club_in_fut_web_app",
        label: "orders.no_club",
        theme: "red",
        image: "/image/status/error.svg",
        description: "orders.no_club_description",
        body: true,
    },
    no_access_to_fifa_21_webapp: {
        btn_text: "orders.resume",
        btn_fnc: "openOrder",
        status: "no_access_to_fifa_21_webapp",
        label: "orders.no_tm",
        theme: "red",
        image: "/image/status/error.svg",
        description: "orders.no_tm_description",
        body: true,
    },
    no_tm: {
        btn_text: "orders.resume",
        btn_fnc: "openOrder",
        status: "no_tm",
        label: "orders.no_tm",
        theme: "red",
        image: "/image/status/error.svg",
        description: "orders.no_tm_description",
        body: true,
    },
    transfer_list_full: {
        btn_text: "orders.resume",
        btn_fnc: "openOrder",
        status: "transfer_list_full",
        label: "orders.list_full_title",
        theme: "red",
        image: "/image/status/error.svg",
        description: "orders.list_full_description",
        body: true,
    },
    login_verification_disabled: {
        btn_text: "orders.resume",
        btn_fnc: "openOrder",
        status: "login_verification_disabled",
        label: "orders.login_disabled",
        theme: "red",
        image: "/image/status/error.svg",
        description: "orders.login_disabled_description",
        body: true,
    },
    finished: {
        btn_text: "orders.repeat",
        btn_fnc: "retryOrder",
        status: "finished",
        label: "orders.finished_title",
        theme: "green",
        image: "/image/status/done.svg",
        description: "orders.finished_description",
        body: false,
    },
    payed: {
        btn_text: "orders.submit",
        btn_fnc: "openOrder",
        status: "payed",
        label: "orders.details",
        theme: "blue",
        image: "/image/status/info.svg",
        description: "orders.details_description",
        body: true,
    },
    accepted: {
        btn_text: "",
        btn_fnc: "openOrder",
        status: "accepted",
        label: "orders.queue",
        theme: "white",
        image: "anime",
        description: "orders.queue_description",
        body: false,
    },
    in_progress: {
        btn_text: "",
        btn_fnc: "openOrder",
        status: "in_progress",
        label: "orders.in_progress",
        theme: "white",
        image: "anime",
        description: "orders.in_progress_description",
        transit_coins: true,
        body: true,
    },
    wrong_backup: {
        btn_text: "orders.resubmit",
        btn_fnc: "openOrder",
        status: "wrong_backup",
        label: "orders.orders.backup_description",
        theme: "red",
        image: "/image/status/warning.svg",
        description: "orders.backup_description",
        body: true,
        wrong_fields: "backup",
    },
    unassigned_items: {
        btn_text: "orders.continue",
        btn_fnc: "openOrder",
        status: "unassigned_items",
        label: "orders.items",
        theme: "red",
        image: "/image/status/warning.svg",
        description: "orders.items_description",
        body: true,
    },
    wrong_credentials: {
        btn_text: "orders.resubmit",
        btn_fnc: "wrongCredentials",
        status: "wrong_credentials",
        label: "orders.wrong_cred",
        theme: "red",
        image: "/image/status/warning.svg",
        description: "orders.wrong_cred_description",
        body: true,
        wrong_fields: "log_pass",
    },
    console_online: {
        btn_text: "orders.resume",
        btn_fnc: "openOrder",
        status: "console_online",
        label: "orders.signed",
        theme: "red",
        image: "/image/status/warning.svg",
        description: "orders.signed_description",
        transit_coins: true,
        body: true,
    },
    online_in_fut_web_app: {
        btn_text: "orders.resume",
        btn_fnc: "openOrder",
        status: "online_in_fut_web_app",
        label: "orders.online",
        theme: "red",
        image: "/image/status/warning.svg",
        description: "orders.online_description",
        transit_coins: true,
        body: true,
    },
    customer_online: {
        btn_text: "orders.resume",
        btn_fnc: "openOrder",
        status: "customer_online",
        label: "orders.signed",
        theme: "red",
        image: "/image/status/warning.svg",
        description: "orders.signed_description",
        transit_coins: true,
        body: true,
    },
    issued_refund: {
        btn_text: "orders.repeat",
        btn_fnc: "retryOrder",
        status: "issued_refund",
        label: "orders.cancelled",
        theme: "white",
        image: "/image/status/done.svg",
        description: "orders.cancelled_description",
        body: false,
    },
    unexpected_error: {
        btn_text: "",
        btn_fnc: "openOrder",
        status: "unexpected_error",
        label: "orders.unexpected",
        theme: "red",
        image: "/image/status/warning.svg",
        description: "orders.unexpected_description",
        body: false,
    },
    temporary_provider_error: {
        btn_text: "",
        btn_fnc: "openOrder",
        status: "temporary_provider_error",
        label: "orders.unknown",
        theme: "red",
        image: "/image/status/warning.svg",
        description: "c",
        body: false,
    },
    undefined_status: {
        btn_text: "",
        btn_fnc: "openOrder",
        status: "undefined_status",
        label: "orders.unknown",
        theme: "red",
        image: "/image/status/error.svg",
        description: "orders.undefined_description",
        body: false,
    },
};
