import type { IReviewsEntity } from "@royalfut/interfaces";

export const reviews: Array<IReviewsEntity> = [
    {
        id: 818,
        title: "Effortless Selling Experience",
        text: "Selling my FIFA coins to RoyalFUT was incredibly smooth. The process was straightforward, and I received payment promptly. Highly recommended for anyone looking to sell their coins hassle-free!",
        username: "Emily K.",
        geo: "United States",
    },
    {
        id: 363,
        title: "Fast and Reliable",
        text: "I sold a large amount of FIFA coins to RoyalFUT and was impressed with their efficiency. They offered competitive rates and the transaction was completed swiftly. Great service overall!",
        username: "Ahmed S.",
        geo: "Saudi Arabia",
    },
    {
        id: 506,
        title: "Trusted Platform for Selling Coins",
        text: "RoyalFUT made it easy for me to sell my excess FIFA coins. The process was secure, and I received payment quickly. I appreciate their reliability and would sell to them again without hesitation.",
        username: "Léa B.",
        geo: "France",
    },
    {
        id: 437,
        title: "Excellent Customer Support",
        text: "I had a few questions before selling my FIFA coins, and the customer support team at RoyalFUT was very helpful. They guided me through the process and ensured everything went smoothly. A great experience overall!",
        username: "Javier M.",
        geo: "Spain",
    },
    {
        id: 750,
        title: "Top-Notch Service",
        text: "Selling FIFA coins to RoyalFUT was a breeze. The website is user-friendly, and the payment was processed quickly. I would recommend them to anyone looking to sell their gaming currency hassle-free.",
        username: "Anastasia P.",
        geo: "Russia",
    },
    {
        id: 254,
        title: "Smooth Transaction",
        text: "I sold 300K FIFA coins to RoyalFUT and was impressed by how quickly and efficiently the transaction was processed. Payment was received promptly, and the entire process was hassle-free. Highly recommended for anyone looking to sell their coins.",
        username: "Hiroshi Y.",
        geo: "Japan",
    },
    {
        id: 693,
        title: "Excellent Service",
        text: "RoyalFUT provided a seamless experience when I sold 500K FIFA coins. The website interface was intuitive, and their rates were competitive. I received payment within hours of completing the transaction. Very satisfied with their service!",
        username: "Elena S.",
        geo: "Italy",
    },
    {
        id: 156,
        title: "Reliable and Trustworthy",
        text: "Selling FIFA coins to RoyalFUT was a breeze. Their platform is secure, and the support team was responsive to my queries. I sold 700K coins and received payment swiftly. Definitely my go-to for future transactions!",
        username: "Carlos R.",
        geo: "Portugal",
    },
    {
        id: 810,
        title: "Efficient and Professional",
        text: "I recently sold 400K FIFA coins through RoyalFUT and was impressed by their professionalism. The process was straightforward, and the payment was processed quickly. I would recommend them to anyone looking to sell their gaming assets.",
        username: "Sophie L.",
        geo: "France",
    },
    {
        id: 609,
        title: "Top-Notch Service",
        text: "RoyalFUT exceeded my expectations when I sold 1 million FIFA coins. The transaction was handled smoothly, and their rates were fair. I received payment promptly, and their customer support team was helpful throughout the process. Highly recommended!",
        username: "Muhammad A.",
        geo: "Saudi Arabia",
    },
    {
        id: 1,
        title: "Fast and Secure",
        text: "I sold 600K FIFA coins to RoyalFUT and was impressed by their efficient service. The transaction was completed within hours, and I received payment via PayPal without any issues. Their platform is trustworthy, and I would sell to them again.",
        username: "Anna K.",
        geo: "Germany",
    },
    {
        id: 2,
        title: "Great Experience",
        text: "Selling FIFA coins to RoyalFUT was straightforward. I sold 800K coins and received payment swiftly. Their customer service was responsive, and I appreciated the transparency throughout the process. Will definitely use their services again.",
        username: "Rafael M.",
        geo: "Mexico",
    },
    {
        id: 3,
        title: "Excellent Platform",
        text: "RoyalFUT offers a reliable platform for selling FIFA coins. I sold 300K coins and received payment within hours. Their rates were competitive, and the process was secure. Highly recommend them for anyone looking to sell gaming currency.",
        username: "Isabella G.",
        geo: "Australia",
    },
    {
        id: 4,
        title: "Effortless Transaction",
        text: "I sold 500K FIFA coins to RoyalFUT and was impressed by their efficiency. The entire process, from listing the coins to receiving payment, was smooth and quick. Their customer support team was also very helpful. Great service overall!",
        username: "Antonio P.",
        geo: "Portugal",
    },
    {
        id: 5,
        title: "Trustworthy Service",
        text: "RoyalFUT is a trustworthy platform for selling FIFA coins. I sold 700K coins and received payment promptly. The process was secure, and their customer service team was responsive to my inquiries. Highly recommended!",
        username: "Yuki T.",
        geo: "Japan",
    },
    {
        id: 6,
        title: "Fast Payment",
        text: "Selling 400K FIFA coins to RoyalFUT was quick and easy. I appreciated their prompt payment and competitive rates. The transaction was completed within hours, and I had no issues throughout the process. Will use their services again!",
        username: "Maximilian S.",
        geo: "Austria",
    },
    {
        id: 7,
        title: "Smooth Process",
        text: "I sold 600K FIFA coins through RoyalFUT and was impressed by their professionalism. The transaction was handled efficiently, and I received payment quickly. Their platform is user-friendly, and I would recommend them to anyone looking to sell gaming currency.",
        username: "Chiara M.",
        geo: "Italy",
    },
    {
        id: 8,
        title: "Great Customer Support",
        text: "Selling FIFA coins to RoyalFUT was a positive experience. Their customer support team was responsive and helped me through the process. I sold 300K coins and received payment promptly. Very satisfied with their service!",
        username: "Lucas H.",
        geo: "Netherlands",
    },
    {
        id: 9,
        title: "Efficient Service",
        text: "I sold 800K FIFA coins to RoyalFUT and was impressed by their efficiency. The transaction was completed swiftly, and I received payment without any issues. Their platform is reliable, and I would recommend them for anyone looking to sell gaming assets.",
        username: "Valentina C.",
        geo: "Argentina",
    },
    {
        id: 10,
        title: "Reliable and Fast",
        text: "RoyalFUT provided a reliable platform for selling FIFA coins. I sold 1 million coins and received payment quickly. The process was straightforward, and their rates were competitive. Will definitely sell to them again in the future!",
        username: "Daniel W.",
        geo: "United States",
    },
    {
        id: 11,
        title: "Smooth and Reliable",
        text: "I sold 500K FIFA coins through RoyalFUT and was impressed with their professionalism. The transaction was seamless, and I received payment promptly. Their customer support team was also very helpful throughout the process. Highly recommended!",
        username: "Sophie M.",
        geo: "United Kingdom",
    },
    {
        id: 12,
        title: "Excellent Service",
        text: "RoyalFUT provided an excellent platform for selling FIFA coins. I sold 700K coins and received payment within hours. The process was secure, and their rates were competitive. I will definitely use their services again!",
        username: "Giovanni P.",
        geo: "Italy",
    },
    {
        id: 13,
        title: "Effortless Transaction",
        text: "Selling FIFA coins to RoyalFUT was effortless. I sold 400K coins and received payment quickly. Their platform is user-friendly, and their customer support team was responsive to my inquiries. Great experience overall!",
        username: "Maria H.",
        geo: "Brazil",
    },
    {
        id: 14,
        title: "Fast and Secure Payment",
        text: "I sold 600K FIFA coins through RoyalFUT and was impressed by their fast and secure payment process. The transaction was completed smoothly, and I received payment via PayPal without any issues. Highly recommend!",
        username: "Johan B.",
        geo: "Sweden",
    },
    {
        id: 15,
        title: "Great Experience",
        text: "I recently sold 800K FIFA coins to RoyalFUT and had a great experience. The transaction was handled efficiently, and I received payment promptly. Their rates were fair, and I would definitely sell to them again.",
        username: "Amira S.",
        geo: "United Arab Emirates",
    },
    {
        id: 16,
        title: "Professional Service",
        text: "RoyalFUT provided a professional service for selling FIFA coins. I sold 300K coins and received payment within hours. Their platform is secure, and their customer support team was very helpful. Highly recommended!",
        username: "Luca G.",
        geo: "Germany",
    },
    {
        id: 17,
        title: "Efficient and Reliable",
        text: "Selling FIFA coins to RoyalFUT was efficient and reliable. I sold 500K coins and received payment quickly. Their rates were competitive, and the process was straightforward. Will use their services again!",
        username: "Elena V.",
        geo: "Russia",
    },
    {
        id: 18,
        title: "Top-Notch Platform",
        text: "RoyalFUT is a top-notch platform for selling FIFA coins. I sold 1 million coins and received payment promptly. The transaction was secure, and their customer service team was responsive. Great service overall!",
        username: "Diego M.",
        geo: "Argentina",
    },
    {
        id: 19,
        title: "Smooth Process",
        text: "Selling FIFA coins through RoyalFUT was a smooth process. I sold 400K coins and received payment swiftly. Their platform is easy to use, and their rates were competitive. Highly recommend them!",
        username: "Emma L.",
        geo: "France",
    },
    {
        id: 20,
        title: "Excellent Customer Support",
        text: "I had a great experience selling FIFA coins to RoyalFUT. Their customer support team was very helpful, and the transaction was completed quickly. I sold 600K coins and received payment without any issues. Will definitely use their services again!",
        username: "Ahmed K.",
        geo: "Saudi Arabia",
    },
    {
        id: 21,
        title: "Trustworthy Platform",
        text: "RoyalFUT is a trustworthy platform for selling FIFA coins. I sold 300K coins and received payment within hours. Their process is transparent, and their rates were fair. I would recommend them to anyone looking to sell gaming currency.",
        username: "Julia R.",
        geo: "Spain",
    },
    {
        id: 22,
        title: "Efficient Service",
        text: "I recently sold 700K FIFA coins through RoyalFUT and was impressed with their efficient service. The transaction was completed quickly, and I received payment promptly. Their platform is secure, and their customer support team was responsive. Great experience overall!",
        username: "Leo C.",
        geo: "Canada",
    },
    {
        id: 23,
        title: "Quick Payment",
        text: "Selling FIFA coins to RoyalFUT was a breeze. I sold 500K coins and received payment swiftly. Their rates were competitive, and their customer service team was helpful throughout the process. Will use their services again!",
        username: "Ana P.",
        geo: "Portugal",
    },
    {
        id: 24,
        title: "Smooth Transaction",
        text: "I sold 800K FIFA coins through RoyalFUT and had a smooth transaction. The payment was processed quickly, and their platform is easy to navigate. Their rates were fair, and I would recommend them for anyone looking to sell gaming assets.",
        username: "Maxim K.",
        geo: "Ukraine",
    },
    {
        id: 25,
        title: "Great Service",
        text: "RoyalFUT provided great service for selling FIFA coins. I sold 600K coins and received payment within hours. Their platform is reliable, and their customer support team was responsive to my inquiries. Highly recommended!",
        username: "Laura S.",
        geo: "Australia",
    },
];
