// страны

const flag_and_currency = [
    {
        title: "USD",
        id: "0",
        country: "",
        url_currency: "/img/USDdrop.svg",
        url_flag: "/img/flag/usd_en.svg",
    },
    {
        currency: "AED",
        title: "AED",
        id: "1",
        country: "",
        url_currency: "/img/aeddrop.svg",
        url_flag: "/img/flag/aed_aed.svg",
    },
    {
        currency: "£",
        title: "GBP",
        id: "2",
        country: "",
        url_currency: "/img/gbpdrop.svg",
        url_flag: "/img/flag/gbp_en.svg",
    },
    {
        currency: "SAR",
        title: "SAR",
        id: "3",
        country: "",
        url_currency: "/img/sardrop.svg",
        url_flag: "/img/flag/sar_sar.svg",
    },
    {
        currency: "€",
        title: "EUR",
        id: "4",
        country: "",
        url_currency: "/img/eurdrop.svg",
        url_flag: "/img/flag/eur_eur.svg",
    },
    {
        currency: "KR",
        title: "SEK",
        id: "5",
        country: "",
        url_currency: "/img/sekdrop.svg",
        url_flag: "/img/flag/sek_sek.svg",
    },
    {
        currency: "C$",
        title: "CAD",
        id: "6",
        country: "",
        url_currency: "/img/caddrop.svg",
        url_flag: "/img/flag/cad_cad.svg",
    },
    {
        currency: "NKr",
        title: "NOK",
        id: "7",
        country: "",
        url_currency: "/img/nokdrop.svg",
        url_flag: "/img/flag/nok_nok.svg",
    },
    {
        currency: "AUD",
        title: "AUD",
        id: "8",
        country: "",
        url_currency: "/img/auddrop.svg",
        url_flag: "/img/flag/aud_aud.svg",
    },
    {
        currency: "PLN",
        title: "PLN",
        id: "9",
        country: "",
        url_currency: "/img/plndrop.svg",
        url_flag: "/img/flag/pln_pln.svg",
    },
    {
        currency: "R$",
        title: "BRL",
        id: "10",
        country: "",
        url_currency: "/img/brldrop.svg",
        url_flag: "/img/flag/brl_brl.svg",
    },
    {
        currency: "TRY",
        title: "TRY",
        id: "11",
        country: "",
        url_currency: "/img/trydrop.svg",
        url_flag: "/img/flag/try_try.svg",
    },

    {
        currency: "₽",
        title: "RUB",
        id: "12",
        country: "",
        url_currency: "/img/rubdrop.svg",
        url_flag: "/img/flag/ru_rub.svg",
    },
];

export default flag_and_currency;
