const pagesData = [
    {
        title: "Barclays Women's Super League TOTS",
        description:
            "Stay updated on player upgrades and discover the essence of FC 24 TOTS, including mixed-league packs and Premier League TOTS.",
        h1: "BWSL",
        h2: "THE FINAL SQUAD",
        cards: [
            "/img/bwsl/1.png",
            "/img/bwsl/2.png",
            "/img/bwsl/3.png",
            "/img/bwsl/4.png",
            "/img/bwsl/5.png",
            "/img/bwsl/6.png",
            "/img/bwsl/7.png",
            "/img/bwsl/8.png",
            "/img/bwsl/9.png",
            "/img/bwsl/10.png",
            "/img/bwsl/11.png",
        ],
        id: 1,
        src: "/img/bwsl.png",
        date: "26th APRIL",
        name: "BWSL",
        route: "/tots/bwsl",
        select: true,
    },
    {
        title: "MIXED LEAGUE TOTS",
        description:
            "Stay updated on player upgrades and discover the essence of FC 24 TOTS, including mixed-league packs and Premier League TOTS.",
        h1: "MIXED LEAGUE TOTS",
        h2: "",
        cards: [
            "/img/mixedleague/1.png",
            "/img/mixedleague/2.png",
            "/img/mixedleague/3.png",
            "/img/mixedleague/4.png",
            "/img/mixedleague/5.png",
            "/img/mixedleague/6.png",
            "/img/mixedleague/7.png",
            "/img/mixedleague/8.png",
            "/img/mixedleague/9.png",
            "/img/mixedleague/10.png",
            "/img/mixedleague/11.png",
            "/img/mixedleague/12.png",
            "/img/mixedleague/13.png",
            "/img/mixedleague/14.png",
            "/img/mixedleague/15.png",
            "/img/mixedleague/16.png",
            "/img/mixedleague/17.png",
            "/img/mixedleague/18.png",
            "/img/mixedleague/19.png",
            "/img/mixedleague/20.png",
            "/img/mixedleague/21.png",
            "/img/mixedleague/22.png",
            "/img/mixedleague/23.png",
        ],
        id: 2,
        src: "/img/mix_l.png",
        date: "26th APR - 31st MAY",
        name: "MIXED LEAGUE",
        route: "/tots/mixed-league",
        select: true,
    },
    {
        title: "Premier League TOTS",
        description:
            "Stay updated on player upgrades and discover the essence of FC 24 TOTS, including mixed-league packs and Premier League TOTS.",
        h1: "Premier League",
        h2: "THE FINAL SQUAD",
        cards: [
            "/img/premierleague/1.png",
            "/img/premierleague/2.png",
            "/img/premierleague/3.png",
            "/img/premierleague/4.png",
            "/img/premierleague/5.png",
            "/img/premierleague/6.png",
            "/img/premierleague/7.png",
            "/img/premierleague/8.png",
            "/img/premierleague/9.png",
            "/img/premierleague/10.png",
            "/img/premierleague/11.png",
            "/img/premierleague/12.png",
            "/img/premierleague/13.png",
            "/img/premierleague/14.png",
            "/img/premierleague/15.png",
            "/img/premierleague/16.png",
            "/img/premierleague/17.png",
            "/img/premierleague/18.png",
            "/img/premierleague/19.png",
            "/img/premierleague/20.png",
        ],
        id: 3,
        src: "/img/pr_l.png",
        date: "26th APRIL",
        name: "PREMIER LEAGUE",
        route: "/tots/premier-league",
        select: true,
    },
    {
        title: "Bundesliga TOTS",
        description:
            "Stay updated on player upgrades and discover the essence of FC 24 TOTS, including mixed-league packs and Premier League TOTS.",
        h1: "Bundesliga",
        h2: "THE FINAL SQUAD",
        cards: [
            "/img/bundesliga/1.png",
            "/img/bundesliga/2.png",
            "/img/bundesliga/3.png",
            "/img/bundesliga/4.png",
            "/img/bundesliga/5.png",
            "/img/bundesliga/6.png",
            "/img/bundesliga/7.png",
            "/img/bundesliga/8.png",
            "/img/bundesliga/9.png",
            "/img/bundesliga/10.png",
            "/img/bundesliga/11.png",
            "/img/bundesliga/12.png",
        ],
        id: 4,
        src: "/img/bundesliga.png",
        date: "3rd MAY",
        name: "BUNDESLIGA",
        route: "/tots/bundesliga",
        select: true,
    },
    {
        title: "Google Pixel Frauen Bundesliga TOTS",
        description:
            "Stay updated on player upgrades and discover the essence of FC 24 TOTS, including mixed-league packs and Premier League TOTS.",
        h1: "Frauen Bundesliga",
        h2: "THE FINAL SQUAD",
        cards: [
            "/img/fraubslga/1.png",
            "/img/fraubslga/2.png",
            "/img/fraubslga/3.png",
            "/img/fraubslga/4.png",
            "/img/fraubslga/5.png",
            "/img/fraubslga/6.png",
            "/img/fraubslga/7.png",
            "/img/fraubslga/8.png",
            "/img/fraubslga/9.png",
            "/img/fraubslga/10.png",
            "/img/fraubslga/11.png",
        ],
        id: 5,
        src: "/img/fraubl.png",
        date: "3rd MAY",
        name: "FRAUEN BUNDESLIGA",
        route: "/tots/frauen-bundesliga",
        select: true,
    },
    { id: 6, src: "/img/live.png", date: "10th MAY", name: "LIVE", route: "" },
    {
        title: "Ligue 1 TOTS",
        description:
            "Stay updated on player upgrades and discover the essence of FC 24 TOTS, including mixed-league packs and Premier League TOTS.",
        h1: "Ligue 1",
        h2: "THE FINAL SQUAD",
        cards: [
            "/img/ligue 1/1.png",
            "/img/ligue 1/2.png",
            "/img/ligue 1/3.png",
            "/img/ligue 1/4.png",
            "/img/ligue 1/5.png",
            "/img/ligue 1/6.png",
            "/img/ligue 1/7.png",
            "/img/ligue 1/8.png",
            "/img/ligue 1/9.png",
            "/img/ligue 1/10.png",
            "/img/ligue 1/11.png",
            "/img/ligue 1/12.png",
            "/img/ligue 1/13.png",
            "/img/ligue 1/14.png",
            "/img/ligue 1/15.png",
            "/img/ligue 1/16.png",
            "/img/ligue 1/17.png",
            "/img/ligue 1/18.png",
            "/img/ligue 1/19.png",
            "/img/ligue 1/20.png",
            "/img/ligue 1/21.png",
            "/img/ligue 1/22.png",
            "/img/ligue 1/23.png",
        ],
        id: 7,
        src: "/img/l1.png",
        date: "10th MAY",
        name: "LIGUE 1",
        route: "/tots/ligue-1",
        select: true,
    },
    {
        title: "D1 Feminine TOTS",
        description:
            "Stay updated on player upgrades and discover the essence of FC 24 TOTS, including mixed-league packs and Premier League TOTS.",
        h1: "Division 1 Feminine TOTS",
        h2: "THE FINAL SQUAD",
        cards: [
            "/img/d1 arkema/1.png",
            "/img/d1 arkema/2.png",
            "/img/d1 arkema/3.png",
            "/img/d1 arkema/4.png",
            "/img/d1 arkema/5.png",
            "/img/d1 arkema/6.png",
            "/img/d1 arkema/7.png",
            "/img/d1 arkema/8.png",
            "/img/d1 arkema/9.png",
            "/img/d1 arkema/10.png",
            "/img/d1 arkema/11.png",
        ],
        id: 8,
        src: "/img/d1.png",
        date: "10th MAY",
        name: "D1 ARKEMA",
        route: "/tots/d1-arkema",
        select: true,
    },
    {
        title: "LaLiga TOTS",
        description:
            "Stay updated on player upgrades and discover the essence of FC 24 TOTS, including mixed-league packs and Premier League TOTS.",
        h1: "LaLiga TOTS",
        h2: "THE FINAL SQUAD",
        cards: [
            "/img/laliga/1.png",
            "/img/laliga/2.png",
            "/img/laliga/3.png",
            "/img/laliga/4.png",
            "/img/laliga/5.png",
            "/img/laliga/6.png",
            "/img/laliga/7.png",
            "/img/laliga/8.png",
            "/img/laliga/9.png",
            "/img/laliga/10.png",
            "/img/laliga/11.png",
            "/img/laliga/12.png",
            "/img/laliga/13.png",
            "/img/laliga/14.png",
            "/img/laliga/15.png",
            "/img/laliga/16.png",
            "/img/laliga/17.png",
            "/img/laliga/18.png",
            "/img/laliga/19.png",
            "/img/laliga/20.png",
            "/img/laliga/21.png",
            "/img/laliga/22.png",
            "/img/laliga/23.png",
        ],
        id: 9,
        src: "/img/laliga.png",
        date: "17th MAY",
        name: "LALIGA",
        route: "/tots/laliga",
        select: true,
    },
    {
        title: "Liga F TOTS",
        description:
            "Stay updated on player upgrades and discover the essence of FC 24 TOTS, including mixed-league packs and Premier League TOTS.",
        h1: "Liga F",
        h2: "THE FINAL SQUAD",
        cards: [
            "/img/liga f/1.png",
            "/img/liga f/2.png",
            "/img/liga f/3.png",
            "/img/liga f/4.png",
            "/img/liga f/5.png",
            "/img/liga f/6.png",
            "/img/liga f/7.png",
            "/img/liga f/8.png",
            "/img/liga f/9.png",
            "/img/liga f/10.png",
            "/img/liga f/11.png",
        ],
        id: 10,
        src: "/img/ligaf.png",
        date: "17th MAY",
        name: "LIGA F",
        route: "/tots/liga-f",
        select: true,
    },
    { id: 11, src: "/img/nwsl.png", date: "24th MAY", name: "NWSL", route: "" },
    {
        id: 12,
        src: "/img/seriea.png",
        date: "24th MAY",
        name: "SERIE A",
        route: "",
    },
    {
        id: 13,
        src: "/img/ultimate.png",
        date: "31st MAY",
        name: "ULTIMATE",
        route: "",
    },
];

export default pagesData;
