import { SOCIAL_CREDENTIALS } from "@royalfut/collections";

const Index = async () => {
    return (
        <div className="flex flex-row self-center">
            <section className="w-full max-w-viewport min-w-viewport mx-auto px-4 md:px-8 flex flex-col mt-12">
                <h1 className="text-6xl font-bold  mb-10">Cookie Policy</h1>
                <p className="leading-5 text-slate-50 text-opacity-80">
                    By using this website and agreeing to this policy, you
                    consent to our use of cookies in accordance with the terms
                    of this policy.
                </p>
                <h2 className="font-bold pt-3 md:pt-6 text-2xl">
                    About cookies
                </h2>
                <p className="text-slate-50 leading-5 text-opacity-80">
                    Cookies are simple text files that are stored on your
                    computer or mobile device by a website’s server. Each cookie
                    is unique to your web browser. It will contain some
                    anonymous information such as a unique identifier, website’s
                    domain name, and some digits and numbers.
                </p>
                <h2 className="font-bold pt-3 md:pt-6 text-2xl">
                    What types of cookies do we use?
                </h2>
                <h3 className="font-bold text-lg pt-4 md:pt-6">
                    Necessary cookies
                </h3>
                <p className="text-slate-50 leading-5 text-opacity-80">
                    Necessary cookies allow us to offer you the best possible
                    experience when accessing and navigating through our website
                    and using its features. For example, these cookies allow us
                    to recognize that you have created an account and have
                    logged into that account.
                </p>
                <h3 className="font-bold text-lg pt-4 md:pt-6">
                    Functionality cookies
                </h3>
                <p className="text-slate-50 leading-5 text-opacity-80">
                    Functionality cookies let us operate the site in accordance
                    with the choices you make. For example, we will recognize
                    your username and remember how you customized the site
                    during future visits.
                </p>
                <h3 className="font-bold text-lg pt-4 md:pt-6">
                    Analytical cookies
                </h3>
                <p className="text-slate-50 leading-5 text-opacity-80">
                    These cookies enable us and third-party services to collect
                    aggregated data for statistical purposes on how our visitors
                    use the website. These cookies do not contain personal
                    information such as names and email addresses and are used
                    to help us improve your user experience of the website.
                </p>
                <h3 className="font-bold text-lg pt-4 md:pt-6">
                    Third party cookies
                </h3>
                <p className="text-slate-50 leading-5 text-opacity-80">
                    When you use the website, you may also be sent third party
                    cookies.
                </p>
                <p className="text-slate-50 leading-5 text-opacity-80">
                    Our advertisers and service providers may send you cookies.
                    They may use the information they obtain from your use of
                    their cookies:
                </p>
                <ol>
                    <li className="text-slate-50 leading-5 text-opacity-80">
                        1. to track your browser across multiple websites
                    </li>
                    <li className="text-slate-50 leading-5 text-opacity-80">
                        2. to build a profile of your web surfing
                    </li>
                    <li className="text-slate-50 leading-5 text-opacity-80">
                        3. to target advertisements based on your interactions
                        with their services, which may be of particular interest
                        to you.
                    </li>
                </ol>
                <p className="text-slate-50 leading-5 text-opacity-80">
                    We use Google Analytics, a web analytics service provided by
                    Google, Inc. (&quot;Google&quot;). Google Analytics uses
                    &quot;cookies&quot;, which are text files placed on your
                    computer, to help the website analyze how users use the
                    site. The information generated by the cookie about your use
                    of the website (including your IP address) will be
                    transmitted to and stored by Google on servers in the United
                    States. The IP address will be truncated before transmission
                    to ensure anonymity. On our behalf, Google will use this
                    information to evaluate your use of the website, compiling
                    reports on website activity and providing other services
                    relating to website activity and internet activity in
                    connection with the use of the website. Google will not
                    associate your IP address with any other data held by
                    Google. You may refuse the use of cookies by selecting the
                    appropriate settings on your browser; however please note
                    that if you do this you may not be able to use the full
                    functionality of this website. In addition to that you may
                    prevent the collection of the information generated by the
                    cookie about your use of the website (including your IP
                    address) and the processing of this data by Google if you
                    download and install the browser plug-in available at the
                    following link:{" "}
                    <a href={"https://tools.google.com/dlpage/gaoptout?hl=en"}>
                        <b>https://tools.google.com/dlpage/gaoptout?hl=en</b>
                    </a>
                </p>
                <h2 className="font-bold pt-3 md:pt-6 text-2xl">
                    Blocking cookies
                </h2>
                <p className="text-slate-50 leading-5 text-opacity-80">
                    Most browsers allow you to refuse to accept cookies. You can
                    find in google.com how to block all cookies in your browser.
                </p>
                <p className="text-slate-50 leading-5 text-opacity-80">
                    Blocking all cookies will, however, have a negative impact
                    upon the usability of many websites. If you block cookies,
                    you may not be able to use certain features on the website
                    (log on, access content, use search functions).
                </p>
                <h2 className="font-bold pt-3 md:pt-6 text-2xl">
                    How to delete cookies?
                </h2>
                <p className="text-slate-50 leading-5 text-opacity-80">
                    If you want to restrict or block the cookies that are set by
                    our website, you can do so through your browser setting.
                    Alternatively, you can visit www.internetcookies.com, which
                    contains comprehensive information on how to do this on a
                    wide variety of browsers and devices. You will find general
                    information about cookies and details on how to delete
                    cookies from your device.
                </p>
                <h2 className="font-bold pt-3 md:pt-6 text-2xl">
                    Contacting us
                </h2>
                <p className="text-slate-50 leading-5 text-opacity-80">
                    If you have any questions regarding this policy or our use
                    of cookies, feel free to reach out to us at{" "}
                    <a
                        href={SOCIAL_CREDENTIALS.mail.support}
                        className="underline underline-offset-2"
                    >
                        {SOCIAL_CREDENTIALS.mail.support}
                    </a>
                    .
                </p>
            </section>
        </div>
    );
};

export default Index;
